dist: trusty
sudo: false
language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - autoconf
    - automake
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - wget
    - zip
    - rerun
    - rerun-bintray
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - MY_REPO=github.com/rerun-modules/rerun-semver
  - BINTRAY_USER=stagrlee
  - BINTRAY_ORG=rerun
  - secure: JWYIgzYTHTu1UMheMq5pAJxAWMytieKZY2MD3CaPAGFxtGPtUQJmA62drfjsa9ar+QSOkqOF74fxQcGCqOQCvXOjnm11xyVjuzN/7Jcov8bLh6Xc6w6AbT4KMh4V/nxu4C69iln9+el9CIlbSWnGOKLXrJSSXXF469O3CvQw0aSBQxot7GkhvSS6/0yN0WiYqpLiuXjdMGyDdQlq8LyOnxfkYK1+8vJZiPA2Pl+e++jfZbJSChdjsaTYOcswWWaTvZcdHtKo4CXgwjGVjcz0S7BT/AdOEpBrk95ceC8T1NSmKk1H/mRerf8/jH+0ZxCgqNlWH72k6OsW3KE7iTAE800yB4JnIoW8Q4lCd7GriAnkCdsiwXK6D2Jhe47udwZLD67HnNSSPEqggJp2H5V3fTw5EUHOo3WUj0SxyWlHtAhbc//MDGN/Sfoca7fEKVgWAI18AkpxB4+DXp0PCU/H6ruyq3hLoHn1t4F+2Ba51zIPZfOpXVsipF7+2s3EI8Wr/yhJV0fhvH++ppQAhCFrul1Nc4LzZ9M9K2af37+7oOF5woAe0dNNgnJCQD4kbK1eCStuRqpcdyZr89aWAdULTKTbPVHlYcFCmhNk/JzUDbjSFkc7TnKBJWa/teruDD8keNV/m3l6fFwfFpt7I4XnWUcH1+h6u2U+0JN//xuDS/w=
  - secure: RQJmdqqeGkIFIrVHK7ycK44L0KDkSYn/c3dlO+BE2ffAKO6QgLPiPJRII4PdlNGcrH5F4xDbiUryoTtacNHzYj3pvAIQOA1BXLEKKQCndAZ245P2OCZvUUBCPG42j/OMnmlLgzZlTPwEWy/5gD0Ur48+LlhF0DE6qehgmwjLXJpugParu8QF1y2I9qYKOiEFqT3bToQ8AlLNIF4z45gwDLM//11x+c3105PPner78zJ/xBKL8sbNQgUu5yNMsrbX0gZLe94xJ+KXjpqii25Hg1qZWNQcdhqr6mu+AAjC7+M+GxoZefGNkNvZ/0zM0nYPvPgKaJFTCanlkuQh47KBUV32ByTDVTfyztZrnu7ECR8uL7n5NMjay/QIajzgYvwGO0vsbhPAmYHSpIdliOWYi8YgKWU44Ogc0u4gTf2KAJMGOt8OD5U+6VJpISeQzFYo9XJPvqUW0gIg3dk56s9YlvCCqJBZY0Eb4pj9zCh4NVSggiLxfGOUHwiVvh5BXge7LFAhKhpoASm8y0k5ku3DDCryv5k9Jl5ZtFSugN2Ko7HWGARFdKBUAcrPjKbTCKFu4Ff7GbX3gzRe2EFL9u4k/kbPYN0PsyeF4tpS6plFzUnEHeMDfsBu8n07TNLAc3e12qlcMOuiBWDkKMYwdxnxgvyXdzLfzn0oBmSpvdbfe1g=
